# home/eldenring.nix
# i wanted a delclarative method of having the dualsense glyphs mod, and i
# wrote a custom script for that since running the .bat files would erase my
# save files on linux. i didnt wanna lose them so i just wrote this because
# i'm lazy.
#
# two things got fixed since the first version:
#   - the launcher no longer needs compatdata/<appid>/version to exist, so it
#     works on the very first launch after a reinstall, and it reuses steam's
#     own command (steam linux runtime included) instead of calling proton
#     directly, which matters on nixos where there's no system python3.
#   - localconfig.vdf is parsed instead of regexed. the old pattern stopped at
#     the first closing brace, which is the one closing the "cloud" sub-block,
#     so LaunchOptions ended up nested inside "cloud" where steam ignores it.

{ config, pkgs, lib, ... }:

let
  gdriveid = "1zX2_8IEmvRsWrtolch_JXqce7QtrAWGG";
  sha256   = "0klvw4rxr12fmankpacvy7qfffaind2hdi93k45b81ii13r71wcg";

  version  = "1.0";

  destDir  = "${config.home.homeDirectory}/Documents/eldenringimportant";
  launchCmd = "${destDir}/launchmod_eldenring.sh %command%";
  eldenRingAppId = "1245620";

  steamUserIds = [ "1201891252" "771323558" ];

  # Fetch the zip from Google Drive
  eldenringZip = pkgs.fetchurl {
    url  = "https://drive.usercontent.google.com/download?id=${gdriveid}&export=download&confirm=t";
    inherit sha256;
    name = "eldenringimportant-${version}.zip";
  };

  # Extract zip into the Nix store
  eldenringStore = pkgs.runCommand "eldenringimportant-${version}" {
    nativeBuildInputs = [ pkgs.unzip ];
  } ''
    mkdir -p $out
    unzip ${eldenringZip} -d $out

    # Zip contains a single top-level folder "eldenringimportant/" — flatten it
    entries=$(ls -1 $out | wc -l)
    topdir=$(ls -1 $out | head -1)
    if [ "$entries" = "1" ] && [ -d "$out/$topdir" ]; then
      shopt -s dotglob
      mv "$out/$topdir"/* "$out/"
      rmdir "$out/$topdir" 2>/dev/null || true
    fi
  '';

  # The launcher is generated here rather than taken from the zip, so the
  # linux-side fixes stay declarative and survive a re-extract.
  launchScript = pkgs.writeShellScript "launchmod_eldenring.sh" ''
    # ModEngine 2 - Elden Ring launcher for Linux (Proton/Steam)
    #
    # Generated by home/eldenring.nix. Edits here are overwritten on the next
    # home-manager activation.
    #
    # Steam expands %command% into our arguments, and on nixos the whole chain
    # matters: it begins with the Steam Linux Runtime entry point, which is
    # what gives Proton an FHS environment (python3 included) to run in. So we
    # pass Steam's own command straight through and swap out only the
    # executable at the end. That also means we don't need Proton to have
    # written compatdata/<appid>/version yet, which it hasn't on a fresh
    # install - the old version of this script deadlocked on exactly that.

    set -uo pipefail

    APPID=1245620

    SCRIPT_DIR=$(cd -- "$(dirname -- "''${BASH_SOURCE[0]}")" && pwd)
    ME2_LAUNCHER=$SCRIPT_DIR/modengine2_launcher.exe
    ME2_CONFIG=$SCRIPT_DIR/config_eldenring.toml

    for required in "$ME2_LAUNCHER" "$ME2_CONFIG"; do
      if [ ! -f "$required" ]; then
        echo "ERROR: missing $required" >&2
        echo "Run a home-manager activation to reinstall ModEngine 2." >&2
        exit 1
      fi
    done

    # ---- launched by Steam: reuse its command, replace the executable -------
    if [ "$#" -gt 0 ]; then
      args=()
      swapped=0

      for arg in "$@"; do
        case "$arg" in
          */start_protected_game.exe|*/eldenring.exe)
            args+=( "$ME2_LAUNCHER" -t er -c "$ME2_CONFIG" )
            swapped=1
            ;;
          *)
            args+=( "$arg" )
            ;;
        esac
      done

      if [ "$swapped" -eq 1 ]; then
        echo "=== ModEngine 2 - Elden Ring (via Steam) ==="
        echo "launcher: $ME2_LAUNCHER"
        echo "config:   $ME2_CONFIG"
        exec "''${args[@]}"
      fi

      echo "WARNING: no Elden Ring executable in the command Steam handed us;" >&2
      echo "         running it unmodified so the game still starts." >&2
      exec "$@"
    fi

    # ---- run by hand: drive Proton ourselves -------------------------------
    STEAM_ROOT=''${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.local/share/Steam}
    COMPAT_DATA=''${STEAM_COMPAT_DATA_PATH:-$STEAM_ROOT/steamapps/compatdata/$APPID}

    PROTON_DIR=""

    if [ -f "$COMPAT_DATA/version" ]; then
      PROTON_VERSION=$(cat "$COMPAT_DATA/version")
      for candidate in \
        "$STEAM_ROOT/steamapps/common/$PROTON_VERSION" \
        "$STEAM_ROOT/steamapps/common/Proton - $PROTON_VERSION" \
        "$STEAM_ROOT/steamapps/common/Proton $PROTON_VERSION" \
        "$HOME/.steam/root/compatibilitytools.d/$PROTON_VERSION" \
        "$STEAM_ROOT/compatibilitytools.d/$PROTON_VERSION"; do
        if [ -d "$candidate" ]; then
          PROTON_DIR=$candidate
          break
        fi
      done
    fi

    # No prefix yet (fresh install): fall back to the newest GE-Proton around.
    if [ -z "$PROTON_DIR" ]; then
      for compat_dir in "$HOME/.steam/root/compatibilitytools.d" \
                        "$STEAM_ROOT/compatibilitytools.d"; do
        [ -d "$compat_dir" ] || continue
        newest=$(ls -1 "$compat_dir" 2>/dev/null | grep '^GE-Proton' | sort -V | tail -1)
        if [ -n "$newest" ]; then
          PROTON_DIR=$compat_dir/$newest
          break
        fi
      done
    fi

    if [ -z "$PROTON_DIR" ] || [ ! -f "$PROTON_DIR/proton" ]; then
      echo "ERROR: couldn't find a Proton build to use." >&2
      echo "Launch Elden Ring from Steam instead, or install GE-Proton into" >&2
      echo "  $HOME/.steam/root/compatibilitytools.d" >&2
      exit 1
    fi

    export STEAM_COMPAT_CLIENT_INSTALL_PATH=$STEAM_ROOT
    export STEAM_COMPAT_DATA_PATH=$COMPAT_DATA
    export STEAM_APP_ID=$APPID
    export SteamAppId=$APPID
    export SteamGameId=$APPID

    mkdir -p "$COMPAT_DATA"

    echo "=== ModEngine 2 - Elden Ring (standalone) ==="
    echo "proton:   $PROTON_DIR"
    echo "prefix:   $COMPAT_DATA"
    echo "launcher: $ME2_LAUNCHER"
    echo "config:   $ME2_CONFIG"

    # Go through the Steam Linux Runtime if it's installed. Proton's own
    # launcher is a python script with a /usr/bin/env python3 shebang, and
    # nixos has no system python3 - outside the runtime container it dies with
    # "env: 'python3': No such file or directory".
    SLR=$STEAM_ROOT/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point
    if [ -x "$SLR" ]; then
      exec "$SLR" --verb=waitforexitandrun -- \
        "$PROTON_DIR/proton" waitforexitandrun \
        "$ME2_LAUNCHER" -t er -c "$ME2_CONFIG"
    fi

    echo "WARNING: SteamLinuxRuntime_sniper not found; calling Proton directly." >&2
    exec "$PROTON_DIR/proton" run "$ME2_LAUNCHER" -t er -c "$ME2_CONFIG"
  '';

  pythonWithVdf = pkgs.python3.withPackages (ps: [ ps.vdf ]);

  # localconfig.vdf is a real nested key-values file. Parse it rather than
  # pattern-matching braces, and clean up anything a previous regex run
  # buried inside a sub-block.
  setLaunchOptions = pkgs.writeText "steam-set-launch-options.py" ''
    import shutil
    import sys

    import vdf

    vdf_path, app_id, launch = sys.argv[1], sys.argv[2], sys.argv[3]


    def child(node, name):
        """Steam treats keys case-insensitively; this module does not."""
        for key in node:
            if key.lower() == name.lower():
                return node[key]
        return None


    def drop(node, name):
        removed = False
        for key in list(node):
            if key.lower() == name.lower():
                del node[key]
                removed = True
        return removed


    with open(vdf_path, encoding="utf-8") as handle:
        data = vdf.load(handle)

    apps = data
    for part in ("UserLocalConfigStore", "Software", "Valve", "Steam", "apps"):
        apps = child(apps, part)
        if apps is None:
            print(f"[steam-launch] no {part} section in {vdf_path}, skipping")
            sys.exit(0)

    app = child(apps, app_id)
    if app is None:
        print(f"[steam-launch] AppID {app_id} not in {vdf_path}, skipping")
        sys.exit(0)

    changed = False

    # An earlier version of this module matched braces with a regex and landed
    # LaunchOptions inside "cloud", where Steam never reads it.
    for name, value in app.items():
        if isinstance(value, dict) and drop(value, "LaunchOptions"):
            print(f"[steam-launch] removed stray LaunchOptions from {app_id}/{name}")
            changed = True

    if child(app, "LaunchOptions") != launch:
        drop(app, "LaunchOptions")
        app["LaunchOptions"] = launch
        changed = True

    if not changed:
        print(f"[steam-launch] AppID {app_id} already correct in {vdf_path}")
        sys.exit(0)

    backup = vdf_path + ".pre-nix.bak"
    try:
        with open(backup, "x", encoding="utf-8"):
            pass
    except FileExistsError:
        pass
    else:
        shutil.copyfile(vdf_path, backup)
        print(f"[steam-launch] kept a copy of the original at {backup}")

    with open(vdf_path, "w", encoding="utf-8") as handle:
        vdf.dump(data, handle, pretty=True)

    print(f"[steam-launch] set LaunchOptions for AppID {app_id} in {vdf_path}")
  '';

in
{
  # Copy ModEngine2 folder to ~/Documents/eldenringimportant/
  # Uses rsync
  home.activation.installEldenRingModEngine = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    VERSION_MARKER="${destDir}/.nix-me2-version"

    if [ ! -f "$VERSION_MARKER" ] || \
       [ "$(cat "$VERSION_MARKER" 2>/dev/null)" != "${version}" ]; then

      $DRY_RUN_CMD mkdir -p \
        "${destDir}/mod" \
        "${destDir}/modengine2/logs"

      $DRY_RUN_CMD ${pkgs.rsync}/bin/rsync \
        --archive --chmod=u+w \
        --ignore-existing \
        --exclude="modengine2/logs/" \
        --exclude="launchmod_eldenring.sh" \
        "${eldenringStore}/" \
        "${destDir}/"

      echo "${version}" > "$VERSION_MARKER"
      echo "ModEngine2: installed/updated to version ${version}"
    else
      echo "ModEngine2: already at version ${version}, skipping"
    fi

    # Always refresh the launcher; rsync --ignore-existing would never update
    # it, and it's the part that actually gets fixes.
    $DRY_RUN_CMD install -Dm755 ${launchScript} "${destDir}/launchmod_eldenring.sh"
  '';

  # Set Steam launch option for Elden Ring
  # Patches localconfig.vdf for all Steam accounts on this machine.
  home.activation.steamEldenRingLaunchOption = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    STEAM_USERDATA="$HOME/.local/share/Steam/userdata"

    if ${pkgs.procps}/bin/pgrep -x steam > /dev/null 2>&1; then
      echo "[steam-launch] WARNING: Steam is running. It rewrites localconfig.vdf"
      echo "[steam-launch]          when it exits, which will undo this. Close Steam"
      echo "[steam-launch]          and re-run the rebuild."
    fi

    for uid in ${lib.concatStringsSep " " steamUserIds}; do
      vdf_file="$STEAM_USERDATA/$uid/config/localconfig.vdf"
      [ -f "$vdf_file" ] || continue

      $DRY_RUN_CMD ${pythonWithVdf}/bin/python3 ${setLaunchOptions} \
        "$vdf_file" "${eldenRingAppId}" "${launchCmd}"
    done
  '';
}
